import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/ui/globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";

// Update these to your new font files with Turkish support
const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.woff2",
  variable: "--font-roboto-regular",
  weight: "400",
});
const robotoBold = localFont({
  src: "./fonts/Roboto-Bold.woff2",
  variable: "--font-roboto-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoRegular.variable} ${robotoBold.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
